// This file is generated by schemagen. Do not edit manually.
import { mutate, query } from '../utils/query';
import type { getCounter, increaseCounter } from '../functions/counter';

export const queryGetCounter = query<typeof getCounter>('get', '/api/counter');
export const mutateIncreaseCounter = mutate<typeof increaseCounter>('post', '/api/counter');
