// This file is generated by assetgen. Do not edit manually.
import asset_1b9dd662 from '@/assets/images/irodori.png?url';
import asset_187b5c11 from '@/assets/images/kaede.png?url';
import asset_9a70e5eb from '@/assets/images/midnightway.png?url';
import asset_2bcab20a from '@/assets/images/tone-marble.png?url';
import asset_d93825e0 from '@/assets/videos/reina.linear.mp4?url';
import asset_f03adc91 from '@/assets/videos/roofrain.mp4?url';
import asset_56ce7f82 from '@/assets/videos/ruri.webm?codecs=vp9:webm,h264:mp4+video';
import { createContext, useEffect, useState } from 'react';
import { createAssetsLoader } from '../utils/assets';
import type { PropsWithChildren } from 'react';

const createRegisteredAssetsLoader = () => {
  const loader = createAssetsLoader();
  loader.add([
    asset_1b9dd662,
    asset_187b5c11,
    asset_9a70e5eb,
    asset_2bcab20a,
    asset_d93825e0,
    asset_f03adc91,
    asset_56ce7f82,
  ]);
  return loader;
};

const globalAssetsLoader = createRegisteredAssetsLoader();
export default globalAssetsLoader;

export const AssetsContext = createContext(globalAssetsLoader);

export const AssetsProvider = ({ children }: PropsWithChildren) => {
  const [assets] = useState(() => createRegisteredAssetsLoader());
  useEffect(() => () => assets.dispose(), [assets]);

  return <AssetsContext.Provider value={assets}>{children}</AssetsContext.Provider>;
};
