// This file is generated by assetgen. Do not edit manually.
import asset_1b9dd662 from '@/assets/images/irodori.png?url';
import asset_187b5c11 from '@/assets/images/kaede.png?url';
import asset_9a70e5eb from '@/assets/images/midnightway.png?url';
import asset_2bcab20a from '@/assets/images/tone-marble.png?url';
import { createContext, useState } from 'react';
import { createAssetsLoader } from '../utils/assets';
import type { PropsWithChildren } from 'react';

const createRegisteredAssetsLoader = () => {
  const loader = createAssetsLoader();
  loader.add([asset_1b9dd662, asset_187b5c11, asset_9a70e5eb, asset_2bcab20a]);
  return loader;
};

const globalAssetsLoader = createRegisteredAssetsLoader();
export default globalAssetsLoader;

export const AssetsContext = createContext(globalAssetsLoader);

export const AssetsProvider = ({ children }: PropsWithChildren) => {
  const [assets] = useState(() => createRegisteredAssetsLoader());

  return <AssetsContext.Provider value={assets}>{children}</AssetsContext.Provider>;
};
